### ISSUE TITLE
编译过程遇到问题请求解答，谢谢。

### ISSUE THREAD

**Issue by Seayouth** [dwindow/dwindow#1]
您好！
我按钮您的build.md的流程编译下来，renderer_prototype的dx9_prototype编译出错。
1>d:\dwindow\dwindow\global_funcs.h(151) : error C2065: “HGESTUREINFO”: 未声明的标识符
1>d:\dwindow\dwindow\global_funcs.h(151) : error C2146: 语法错误 : 缺少“)”(在标识符“hGestureInfo”的前面)
1>d:\dwindow\dwindow\global_funcs.h(151) : error C2059: 语法错误 : “)”
其他地方都编译正常，但是最后运行.bat后报错没法生成StereoPlayer.exe。
我看了下dx9_prototype的附加包含目录有一个“E:\DS_SDK_LITE\BaseClasses;”我想是不是缺了这个包含目录的缘故呢？如果不是，请问可能是哪里出问题了呢？
谢谢！

**Comment by my12doom** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dd353235(v=vs.85).aspx

参考这里，HGESTUREINFO需要至少Windows 7 SDK。
